apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}



apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
{{- toYaml .Values.djangoConfig | nindent 2 }}
